### ISSUE TITLE
Updating to Phosphor 2.1

### ISSUE THREAD

**Issue by martrik** [maful/ruby-phosphor-icons#3]
Hello! Phosphor released a new version (2.1) on the 31st of March. Would you be able to update the core reference to their release commit? I'm also happy to submit a PR for it if needed. Thanks!

**Comment by Michoels** [comment]
This would be great!

**Comment by martrik** [comment]
Hey @maful, would you be open to adding it collaborators to the repo so they can take care of keeping the gem updated?

**Comment by maful** [comment]
Hi @martrik, yes feel free to open a PR

**Comment by martrik** [comment]
Here you go @maful https://github.com/maful/ruby-phosphor-icons/pull/4

**Comment by maful** [comment]
Hey all,

Released [v0.3.0](https://github.com/maful/ruby-phosphor-icons/releases/tag/v0.3.0)

Thanks
